var Settings = {
    days: ["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota"],
    control: true,
    sign: ['ą', 'ć', 'ę', 'ł', 'ń', 'ó', 'ś', 'ź', 'ż', ' '],
    signUTF: ['%C4%85', '%C4%87', '%C4%99', '%C5%82', '%C5%84', '%C3%B3', '%C5%9B', '%C5%BA', '%C5%BC', '%20'],
    //google map design array/ style var names
    stylesTab: [
        { styleName: "multiMapStyle", name: multiMapStyle, visibleName: "Multi Brand Network", id: "mapMulti" },
        { styleName: "lightMapStyle", name: lightMapStyle, visibleName: "Light Grey", id: "mapLight" },
        { styleName: "paleMapStyle", name: paleMapStyle, visibleName: "Pale Dawn", id: "mapPale" },
        { styleName: "assinMapStyle", name: assinMapStyle, visibleName: "Assassin's Creed IV", id: "mapAssassin" },
        { styleName: "appleMapStyle", name: appleMapStyle, visibleName: "Apple Maps-esque", id: "mapApple" },
        { styleName: "grayMapStyle", name: grayMapStyle, visibleName: "Shades of Grey", id: "mapShades" },
        { styleName: "natureMapStyle", name: natureMapStyle, visibleName: "Nature", id: "mapNature" },
        { styleName: "bentleyMapStyle", name: bentleyMapStyle, visibleName: "Bentley", id: "mapBentley" },
        { styleName: "cobaltMapStyle", name: cobaltMapStyle, visibleName: "Cobalt custom", id: "mapCobalt" },
        { styleName: "sinCityMapStyle", name: sinCityMapStyle, visibleName: "Sin City", id: "mapSinCity" },
        { styleName: "redMapStyle", name: redMapStyle, visibleName: "Red Map", id: "mapRed" },
        { styleName: "lightMonochromeMapStyle", name: lightMonochromeMapStyle, visibleName: "Light Monochrome Bluish", id: "mapLightMonochrome" },
        { styleName: "lightGreenMapStyle", name: lightGreenMapStyle, visibleName: "Light Green", id: "mapGreen" },
        { styleName: "lightDreamMapStyle", name: lightDreamMapStyle, visibleName: "Light Dream", id: "mapDream" },
        { styleName: "MidnightMapStyle", name: MidnightMapStyle, visibleName: "Midnight Commander", id: "mapMidnight" },
        { styleName: "NeutralMapStyle", name: NeutralMapStyle, visibleName: "Neutral Blue", id: "mapNeutral" },
        { styleName: "LunarMapStyle", name: LunarMapStyle, visibleName: "Lunar Landscape", id: "mapLunar" },
        { styleName: "HuesMapStyle", name: HuesMapStyle, visibleName: "Red Hues", id: "mapHues" },
        { styleName: "RedDarknessMapStyle", name: RedDarknessMapStyle, visibleName: "Red Darkness", id: "mapDarkness" },
        { styleName: "CaptorMapStyle", name: CaptorMapStyle, visibleName: "Captor", id: "mapCaptor" },
        { styleName: "papuportalMapStyle", name: papuportalMapStyle, visibleName: "Papuportal", id: "mapPapu" },
        { styleName: "DarkYellowMapStyle", name: DarkYellowMapStyle, visibleName: "Dark Yellow", id: "mapDarkYellow" },
        { styleName: "CLRMapStyle", name: CLRMapStyle, visibleName: "CLR Map", id: "mapCLT" },
        { styleName: "MonochromeTerrainMapStyle", name: MonochromeTerrainMapStyle, visibleName: "Monochrome terrain", id: "mapTerrain" },
    ],
    //google pins array/ image names
    pinsTab: [
        "pin0",
        "pin1",
        "pin2",
        "pin3",
        "pin4",
        "pin5",
        "pin6",
        "pin7",
        "pin8",
        "pin9",
        "pin10",
        "pin11",
        "pin12",
    ],
    curentLat: null,
    curentLan: null,
}